// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VentifyAPI.Data;

#nullable disable

namespace VentifyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251122222026_AddProductosVentas")]
    partial class AddProductosVentas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VentifyAPI.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("subtotal");

                    b.Property<int?>("VarianteProductoId")
                        .HasColumnType("int")
                        .HasColumnName("variante_producto_id");

                    b.Property<int>("VentaId")
                        .HasColumnType("int")
                        .HasColumnName("venta_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VarianteProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("detalles_venta", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Negocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<string>("NombreNegocio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_negocio");

                    b.HasKey("Id");

                    b.ToTable("negocios", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext")
                        .HasColumnName("categoria");

                    b.Property<string>("CodigoBarras")
                        .HasColumnType("longtext")
                        .HasColumnName("codigo_barras");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("imagen_url");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio_compra");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio_venta");

                    b.Property<int>("StockActual")
                        .HasColumnType("int")
                        .HasColumnName("stock_actual");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int")
                        .HasColumnName("stock_minimo");

                    b.Property<string>("Subcategoria")
                        .HasColumnType("longtext")
                        .HasColumnName("subcategoria");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("longtext")
                        .HasColumnName("unidad_medida");

                    b.HasKey("Id");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.PuntoDeVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int")
                        .HasColumnName("negocio_id");

                    b.Property<string>("NombrePunto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_punto");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.ToTable("puntos_de_venta", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<int?>("NegocioId")
                        .HasColumnType("int")
                        .HasColumnName("negocio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("dueño")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("NegocioId");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.VarianteProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .HasColumnType("longtext")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("variantes_producto", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("forma_pago");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int")
                        .HasColumnName("negocio_id");

                    b.Property<string>("Ticket")
                        .HasColumnType("longtext")
                        .HasColumnName("ticket");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_pagado");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.DetalleVenta", b =>
                {
                    b.HasOne("VentifyAPI.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentifyAPI.Models.VarianteProducto", "VarianteProducto")
                        .WithMany()
                        .HasForeignKey("VarianteProductoId");

                    b.HasOne("VentifyAPI.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("VarianteProducto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("VentifyAPI.Models.PuntoDeVenta", b =>
                {
                    b.HasOne("VentifyAPI.Models.Negocio", "Negocio")
                        .WithMany("PuntosDeVenta")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("VentifyAPI.Models.Usuario", b =>
                {
                    b.HasOne("VentifyAPI.Models.Negocio", "Negocio")
                        .WithMany("Usuarios")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("VentifyAPI.Models.VarianteProducto", b =>
                {
                    b.HasOne("VentifyAPI.Models.Producto", "Producto")
                        .WithMany("Variantes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("VentifyAPI.Models.Venta", b =>
                {
                    b.HasOne("VentifyAPI.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentifyAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VentifyAPI.Models.Negocio", b =>
                {
                    b.Navigation("PuntosDeVenta");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("VentifyAPI.Models.Producto", b =>
                {
                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("VentifyAPI.Models.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
