// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VentifyAPI.Data;

#nullable disable

namespace VentifyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251122205743_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VentifyAPI.Models.Negocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<string>("NombreNegocio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_negocio");

                    b.HasKey("Id");

                    b.ToTable("negocios", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.PuntoDeVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int")
                        .HasColumnName("negocio_id");

                    b.Property<string>("NombrePunto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_punto");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.ToTable("puntos_de_venta", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<int?>("NegocioId")
                        .HasColumnType("int")
                        .HasColumnName("negocio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("dueño")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("NegocioId");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.PuntoDeVenta", b =>
                {
                    b.HasOne("VentifyAPI.Models.Negocio", "Negocio")
                        .WithMany("PuntosDeVenta")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("VentifyAPI.Models.Usuario", b =>
                {
                    b.HasOne("VentifyAPI.Models.Negocio", "Negocio")
                        .WithMany("Usuarios")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("VentifyAPI.Models.Negocio", b =>
                {
                    b.Navigation("PuntosDeVenta");

                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
