// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VentifyAPI.Data;

#nullable disable

namespace VentifyAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251201045547_AddDescuentosToProducto")]
    partial class AddDescuentosToProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VentifyAPI.Models.Caja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_caja");

                    b.Property<bool>("Abierta")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("abierta");

                    b.Property<string>("AbiertaPor")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("abierta_por");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_apertura");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_cierre");

                    b.Property<decimal>("MontoActual")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("monto_actual");

                    b.Property<decimal?>("MontoCierre")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("monto_cierre");

                    b.Property<decimal>("MontoInicial")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("monto_inicial");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int")
                        .HasColumnName("negocio_id");

                    b.Property<string>("ResumenCierre")
                        .HasColumnType("longtext")
                        .HasColumnName("resumen_cierre");

                    b.Property<string>("Turno")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("turno");

                    b.Property<int>("UsuarioAperturaId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_apertura_id");

                    b.Property<int?>("UsuarioCierreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("cajas", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext")
                        .HasColumnName("direccion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_creacion");

                    b.Property<decimal>("LimiteCredito")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("limite_credito");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int")
                        .HasColumnName("negocio_id");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("Notas")
                        .HasColumnType("longtext")
                        .HasColumnName("notas");

                    b.Property<string>("RFC")
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("rfc");

                    b.Property<decimal>("SaldoActual")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("saldo_actual");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId", "NombreCompleto");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.DetalleVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("subtotal");

                    b.Property<int?>("VarianteProductoId")
                        .HasColumnType("int")
                        .HasColumnName("variante_producto_id");

                    b.Property<int>("VentaId")
                        .HasColumnType("int")
                        .HasColumnName("venta_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VarianteProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("detalles_venta", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.MermaEvento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_utc");

                    b.Property<int>("MermaAntes")
                        .HasColumnType("int")
                        .HasColumnName("merma_antes");

                    b.Property<int>("MermaDespues")
                        .HasColumnType("int")
                        .HasColumnName("merma_despues");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("motivo");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int")
                        .HasColumnName("negocio_id");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<int>("StockAntes")
                        .HasColumnType("int")
                        .HasColumnName("stock_antes");

                    b.Property<int>("StockDespues")
                        .HasColumnType("int")
                        .HasColumnName("stock_despues");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("merma_eventos", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Negocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ColorAcento")
                        .HasColumnType("longtext");

                    b.Property<string>("ColorFondo")
                        .HasColumnType("longtext");

                    b.Property<string>("ColorPrimario")
                        .HasColumnType("longtext");

                    b.Property<string>("ColorSecundario")
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext");

                    b.Property<string>("GiroComercial")
                        .HasColumnType("longtext");

                    b.Property<bool>("ModoOscuro")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreNegocio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_negocio");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<string>("RFC")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("negocios", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<int>("CantidadInicial")
                        .HasColumnType("int")
                        .HasColumnName("cantidad_inicial");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext")
                        .HasColumnName("categoria");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<string>("CodigoBarras")
                        .HasColumnType("longtext")
                        .HasColumnName("codigo_barras");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("DescuentoFechaFin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("descuento_fecha_fin");

                    b.Property<DateTime?>("DescuentoFechaInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("descuento_fecha_inicio");

                    b.Property<TimeSpan?>("DescuentoHoraFin")
                        .HasColumnType("time(6)")
                        .HasColumnName("descuento_hora_fin");

                    b.Property<TimeSpan?>("DescuentoHoraInicio")
                        .HasColumnType("time(6)")
                        .HasColumnName("descuento_hora_inicio");

                    b.Property<decimal?>("DescuentoPorcentaje")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("descuento_porcentaje");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("imagen_url");

                    b.Property<int>("Merma")
                        .HasColumnType("int")
                        .HasColumnName("merma");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int")
                        .HasColumnName("negocio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio_compra");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio_venta");

                    b.Property<int>("StockActual")
                        .HasColumnType("int")
                        .HasColumnName("stock_actual");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int")
                        .HasColumnName("stock_minimo");

                    b.Property<string>("Subcategoria")
                        .HasColumnType("longtext")
                        .HasColumnName("subcategoria");

                    b.Property<string>("UnidadMedida")
                        .HasColumnType("longtext")
                        .HasColumnName("unidad_medida");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_proveedor");

                    b.Property<string>("Correo")
                        .HasColumnType("longtext")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .HasColumnType("longtext")
                        .HasColumnName("direccion");

                    b.Property<int?>("NegocioId")
                        .HasColumnType("int")
                        .HasColumnName("negocio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("proveedores", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.PuntoDeVenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int")
                        .HasColumnName("negocio_id");

                    b.Property<string>("NombrePunto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nombre_punto");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.ToTable("puntos_de_venta", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("revoked");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("token");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "Revoked");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Reports.InventarioPorCategoriaView", b =>
                {
                    b.Property<int>("CantidadInicialTotal")
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("MermaTotal")
                        .HasColumnType("int");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int");

                    b.Property<int>("ProductosCount")
                        .HasColumnType("int");

                    b.Property<int>("StockTotal")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_inventario_por_categoria", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Reports.ProductoStockBajoView", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_productos_stock_bajo", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Reports.VentasPorAnioView", b =>
                {
                    b.Property<DateTime>("Anio")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("VentasCount")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_ventas_por_anio", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Reports.VentasPorDiaView", b =>
                {
                    b.Property<DateTime>("Dia")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("VentasCount")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_ventas_por_dia", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Reports.VentasPorMesView", b =>
                {
                    b.Property<DateTime>("Mes")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("VentasCount")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_ventas_por_mes", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Apellido1")
                        .HasColumnType("longtext");

                    b.Property<string>("Apellido2")
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("correo");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("creado_en");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("longtext");

                    b.Property<int?>("NegocioId")
                        .HasColumnType("int")
                        .HasColumnName("negocio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NumeroSeguroSocial")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Puesto")
                        .HasColumnType("longtext");

                    b.Property<string>("RFC")
                        .HasColumnType("longtext");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("dueño")
                        .HasColumnName("rol");

                    b.Property<decimal?>("SueldoDiario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("NegocioId");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.VarianteProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .HasColumnType("longtext")
                        .HasColumnName("codigo");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int")
                        .HasColumnName("producto_id");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.ToTable("variantes_producto", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Venta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<decimal?>("Cambio")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("cambio");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_hora");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("forma_pago");

                    b.Property<decimal?>("MontoRecibido")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("monto_recibido");

                    b.Property<int>("NegocioId")
                        .HasColumnType("int")
                        .HasColumnName("negocio_id");

                    b.Property<string>("Ticket")
                        .HasColumnType("longtext")
                        .HasColumnName("ticket");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("total_pagado");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NegocioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("VentifyAPI.Models.Category", b =>
                {
                    b.HasOne("VentifyAPI.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VentifyAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VentifyAPI.Models.DetalleVenta", b =>
                {
                    b.HasOne("VentifyAPI.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentifyAPI.Models.VarianteProducto", "VarianteProducto")
                        .WithMany()
                        .HasForeignKey("VarianteProductoId");

                    b.HasOne("VentifyAPI.Models.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("VarianteProducto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("VentifyAPI.Models.MermaEvento", b =>
                {
                    b.HasOne("VentifyAPI.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentifyAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VentifyAPI.Models.Producto", b =>
                {
                    b.HasOne("VentifyAPI.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VentifyAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VentifyAPI.Models.PuntoDeVenta", b =>
                {
                    b.HasOne("VentifyAPI.Models.Negocio", "Negocio")
                        .WithMany("PuntosDeVenta")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("VentifyAPI.Models.RefreshToken", b =>
                {
                    b.HasOne("VentifyAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VentifyAPI.Models.Usuario", b =>
                {
                    b.HasOne("VentifyAPI.Models.Negocio", "Negocio")
                        .WithMany("Usuarios")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("VentifyAPI.Models.VarianteProducto", b =>
                {
                    b.HasOne("VentifyAPI.Models.Producto", "Producto")
                        .WithMany("Variantes")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("VentifyAPI.Models.Venta", b =>
                {
                    b.HasOne("VentifyAPI.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");

                    b.HasOne("VentifyAPI.Models.Negocio", "Negocio")
                        .WithMany()
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VentifyAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Negocio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("VentifyAPI.Models.Category", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("VentifyAPI.Models.Negocio", b =>
                {
                    b.Navigation("PuntosDeVenta");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("VentifyAPI.Models.Producto", b =>
                {
                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("VentifyAPI.Models.Venta", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
